Resources:
  queue276F7297:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: random-number-queue-10
  publishLayer99BDE665:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: template-factory-asset-bucket
        S3Key: publish/dependencies.zip
  publishLambdaServiceRole01A1B78A:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  publishLambdaServiceRoleDefaultPolicy9A05D5B5:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:SendMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - queue276F7297
                - Arn
        Version: 2012-10-17
      PolicyName: publishLambdaServiceRoleDefaultPolicy9A05D5B5
      Roles:
        - Ref: publishLambdaServiceRole01A1B78A
  publishLambda8B016DDA:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: template-factory-asset-bucket
        S3Key: publish/deployment.zip
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - publishLambdaServiceRole01A1B78A
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          QUEUE_URL:
            Ref: queue276F7297
          MAXIMUM: "10"
      Layers:
        - Ref: publishLayer99BDE665
    DependsOn:
      - publishLambdaServiceRoleDefaultPolicy9A05D5B5
      - publishLambdaServiceRole01A1B78A
  publishEndpoint50F2BEB0:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: publishEndpoint
  publishEndpointDeployment6E4AE3812ca46aa6a7ebc8afde8227dbb26b9db5:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: publishEndpoint50F2BEB0
      Description: Automatically created by the RestApi construct
    DependsOn:
      - publishEndpointproxyANY91F5EDA2
      - publishEndpointproxyCB70907E
      - publishEndpointANY267BACCF
  publishEndpointDeploymentStageprodC5D71015:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: publishEndpoint50F2BEB0
      DeploymentId:
        Ref: publishEndpointDeployment6E4AE3812ca46aa6a7ebc8afde8227dbb26b9db5
      StageName: prod
  publishEndpointCloudWatchRole43EC15D9:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
  publishEndpointAccount94C10C79:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - publishEndpointCloudWatchRole43EC15D9
          - Arn
    DependsOn:
      - publishEndpoint50F2BEB0
  publishEndpointproxyCB70907E:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - publishEndpoint50F2BEB0
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: publishEndpoint50F2BEB0
  publishEndpointproxyANYApiPermissionrandomNumberStackpublishEndpoint81A19095ANYproxyF499C264:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - publishLambda8B016DDA
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-east-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: publishEndpoint50F2BEB0
            - /
            - Ref: publishEndpointDeploymentStageprodC5D71015
            - /*/{proxy+}
  publishEndpointproxyANYApiPermissionTestrandomNumberStackpublishEndpoint81A19095ANYproxy53132771:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - publishLambda8B016DDA
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-east-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: publishEndpoint50F2BEB0
            - /test-invoke-stage/*/{proxy+}
  publishEndpointproxyANY91F5EDA2:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: publishEndpointproxyCB70907E
      RestApiId:
        Ref: publishEndpoint50F2BEB0
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - publishLambda8B016DDA
                  - Arn
              - /invocations
  publishEndpointANYApiPermissionrandomNumberStackpublishEndpoint81A19095ANY0857F3A0:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - publishLambda8B016DDA
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-east-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: publishEndpoint50F2BEB0
            - /
            - Ref: publishEndpointDeploymentStageprodC5D71015
            - /*/
  publishEndpointANYApiPermissionTestrandomNumberStackpublishEndpoint81A19095ANY83791DFD:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - publishLambda8B016DDA
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:us-east-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: publishEndpoint50F2BEB0
            - /test-invoke-stage/*/
  publishEndpointANY267BACCF:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - publishEndpoint50F2BEB0
          - RootResourceId
      RestApiId:
        Ref: publishEndpoint50F2BEB0
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - publishLambda8B016DDA
                  - Arn
              - /invocations
  randomnumbertableC0A520A9:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  subscribeLayerED8E202C:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: template-factory-asset-bucket
        S3Key: subscribe/dependencies.zip
  subscribeLambdaServiceRoleB7F31258:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  subscribeLambdaServiceRoleDefaultPolicy768CD973:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:ReceiveMessage
              - sqs:ChangeMessageVisibility
              - sqs:GetQueueUrl
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - queue276F7297
                - Arn
          - Action:
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - randomnumbertableC0A520A9
                  - Arn
              - Ref: AWS::NoValue
        Version: 2012-10-17
      PolicyName: subscribeLambdaServiceRoleDefaultPolicy768CD973
      Roles:
        - Ref: subscribeLambdaServiceRoleB7F31258
  subscribeLambda023905A9:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: template-factory-asset-bucket
        S3Key: subscribe/deployment.zip
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - subscribeLambdaServiceRoleB7F31258
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          TABLE_NAME:
            Ref: randomnumbertableC0A520A9
      Layers:
        - Ref: subscribeLayerED8E202C
    DependsOn:
      - subscribeLambdaServiceRoleDefaultPolicy768CD973
      - subscribeLambdaServiceRoleB7F31258
  subscribeLambdaSqsEventSourcerandomNumberStackqueue081B7A2809078112:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn:
        Fn::GetAtt:
          - queue276F7297
          - Arn
      FunctionName:
        Ref: subscribeLambda023905A9
Outputs:
  publishEndpoint76D94F39:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: publishEndpoint50F2BEB0
          - .execute-api.us-east-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: publishEndpointDeploymentStageprodC5D71015
          - /
